spring:
  profiles:
    active: local

  # Performance tuning
  jpa:
    open-in-view: false

    properties:
      hibernate:
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true

        query:
          plan_cache_max_size: 4096
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true


      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE