/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.developersboard;

final class App {
  private App() {
    // Prevent instantiation
    // Optional: throw an exception e.g. AssertionError
    // if this ever *is* called
    throw new AssertionError("Instantiating utility class...");
  }

  public static void main(String[] args) {
    // main method stuff
  }
}
