/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.developersboard;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * The class has the main method to get the application started.
 *
 * @author Eric Opoku
 * @version 1.0
 * @since 1.0
 */
@Slf4j
@SpringBootApplication
class Upsidle {

  /**
   * The application's entry point.
   *
   * @param args an array of command-line arguments for the application
   */
  public static void main(String[] args) {
    SpringApplication.run(Upsidle.class, args);
  }
}
