/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.developersboard;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@Slf4j
@SpringBootApplication
class Upsidle {

  public static void main(String[] args) {
    SpringApplication.run(Upsidle.class, args);
  }
}
